import Head from 'next/head'
import StrapiClient from '../lib/strapi-client'
import styles from '../styles/Home.module.css'

export default function Home({posts}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <main>Hello Blog!</main>
    {
      posts.map(post => (
        <div key={post.id}>{post.title}</div>
      ))
    }
    </div>
  )
}
const client = new StrapiClient();
export const getStaticProps = async () => {
  const posts = await client.getPosts();
  return { props: { posts } }
}
