import Head from 'next/head'
import StrapiClient from '../lib/strapi-client'
import PostList from '../components/Post/PostList'

export default function Articles({posts}) {
    return (
        <div>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <PostList title="All Posts" posts={posts} />
        </div>
      )
}

const client = new StrapiClient();
export const getStaticProps = async () => {
  const posts = await client.getPosts();
  return { props: { posts } }
}
